background="#282828"
text="#ebdbb2"
subtle="#d79921"
warning-text="#cc241d"
text-special-one="#83a598"
text-special-two="#d3869b"
top-bar-background="#665c54"
top-bar-text="#282828"
status-bar-background="#665c54"
status-bar-text="#282828"
status-bar-view-background="#458588"
status-bar-view-text="#282828"
list-selected-background="#83a598"
list-selected-text="#282828"
command-text="#665c54"
list-selected-inactive-background="#665c54"
list-selected-inactive-text="#282828"
controls-text="#665c54"
controls-highlight="#d3869b"
autocomplete-background="#282828"
autocomplete-text="#665c54"
autocomplete-selected-background="#458588"
autocomplete-selected-text="#282828"
button-color-one="#665c54"
button-color-two="#282828"
timeline-name-background="#282828"
timeline-name-text="#665c54"
